title: Cloud things. lol.
description: Tactile is a theme for GitHub Pages. Just playing around before there will be something meaningful.
show_downloads: true
google_analytics:
  theme: jekyll-theme-tactile